// <auto-generated />
using System;
using DotNet_Starter_Template.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet_Starter_Template.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117151552_CreateMenuManagementTables")]
    partial class CreateMenuManagementTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Component")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Feature")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Page")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacementId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubModule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Create",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3221),
                            Description = "Create users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Create",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Read",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3243),
                            Description = "View users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Read",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Update",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3246),
                            Description = "Update users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Update",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Delete",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3248),
                            Description = "Delete users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Delete",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Activate",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3250),
                            Description = "Activate/deactivate users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Activate",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 6,
                            Action = "ResetPassword",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3254),
                            Description = "Reset user passwords",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.ResetPassword",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 7,
                            Action = "AssignRoles",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3256),
                            Description = "Assign roles to users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.AssignRoles",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 8,
                            Action = "ViewAuditLog",
                            Category = "Audit",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3257),
                            Description = "View user audit logs",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.ViewAuditLog",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Create",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3259),
                            Description = "Create roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Create",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Read",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3262),
                            Description = "View roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Read",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 11,
                            Action = "Update",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3266),
                            Description = "Update roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Update",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Delete",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3267),
                            Description = "Delete roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Delete",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 13,
                            Action = "AssignPermissions",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3283),
                            Description = "Assign permissions to roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.AssignPermissions",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 14,
                            Action = "AssignUsers",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3285),
                            Description = "Assign users to roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.AssignUsers",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 15,
                            Action = "Create",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3287),
                            Description = "Create permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Create",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 16,
                            Action = "Read",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3288),
                            Description = "View permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Read",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 17,
                            Action = "Update",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3290),
                            Description = "Update permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Update",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 18,
                            Action = "Delete",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3293),
                            Description = "Delete permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Delete",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 19,
                            Action = "Assign",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3295),
                            Description = "Assign permissions to roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Assign",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 20,
                            Action = "Settings",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3296),
                            Description = "Manage system settings",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Settings",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 21,
                            Action = "Backup",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3298),
                            Description = "Create system backups",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Backup",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 22,
                            Action = "Restore",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3299),
                            Description = "Restore system backups",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Restore",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 23,
                            Action = "Logs",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3301),
                            Description = "View system logs",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Logs",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 24,
                            Action = "Monitoring",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3303),
                            Description = "System monitoring access",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Monitoring",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 25,
                            Action = "Maintenance",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3304),
                            Description = "System maintenance access",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Maintenance",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentRoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Category = "System",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3474),
                            Description = "Full system access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN",
                            Priority = 1
                        },
                        new
                        {
                            Id = "2",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3602),
                            Description = "Administrative access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Priority = 2
                        },
                        new
                        {
                            Id = "3",
                            Category = "Management",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3607),
                            Description = "Management access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            Priority = 3
                        },
                        new
                        {
                            Id = "4",
                            Category = "User",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3622),
                            Description = "Basic user access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER",
                            Priority = 4
                        },
                        new
                        {
                            Id = "5",
                            Category = "Guest",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3625),
                            Description = "Limited guest access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Guest",
                            NormalizedName = "GUEST",
                            Priority = 5
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "1",
                            PermissionId = 1,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(861),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 2,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(866),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 3,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(957),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 4,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(959),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 5,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(960),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 6,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(961),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 7,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(963),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 8,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(965),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 9,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(965),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 10,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(966),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 11,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(966),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 12,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(967),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 13,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(967),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 14,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(968),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 15,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(969),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 16,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(970),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 17,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(970),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 18,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(971),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 19,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(972),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 20,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(973),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 21,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(974),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 22,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(974),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 23,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(976),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 24,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(976),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 25,
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(977),
                            AssignedBy = "System",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Theme")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2bdc1d64-19ee-4979-89d1-b86d2d388e93",
                            CreatedAt = new DateTime(2025, 11, 17, 15, 15, 51, 659, DateTimeKind.Utc).AddTicks(3800),
                            Email = "superadmin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            IsActive = true,
                            Language = "en",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@EXAMPLE.COM",
                            NormalizedUserName = "SUPERADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENlouKfUrfZu7/x5eS7zFryHXpvIjbq0qskJQB7GgxKrVzHH8jjlW8NzY0WdBNF9sA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5123f419-1e28-4342-b2f6-a5a1eac3816c",
                            Theme = "light",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@example.com"
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1",
                            AssignedAt = new DateTime(2025, 11, 17, 15, 15, 51, 793, DateTimeKind.Utc).AddTicks(639),
                            AssignedBy = "System",
                            IsActive = true,
                            IsPrimary = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.UserRole", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
