// <auto-generated />
using System;
using DotNet_Starter_Template.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet_Starter_Template.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202231014_AddUserIdToCustomers")]
    partial class AddUserIdToCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Categories_CreatedAt");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_Categories_DisplayOrder");

                    b.HasIndex("IsVisible")
                        .HasDatabaseName("IX_Categories_IsVisible");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_Name");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Categories_UpdatedAt");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DefaultPaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FirstOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoyaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferredLanguage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en");

                    b.Property<bool>("PromotionalEmails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SavedPaymentMethods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Customers_CreatedAt");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customers_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Customers_IsActive");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Customers_Phone");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Customers_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Home");

                    b.Property<string>("Apartment")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_CustomerAddresses_City");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_CustomerAddresses_CustomerId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CustomerAddresses_IsActive");

                    b.HasIndex("CustomerId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("UQ_CustomerAddresses_DefaultPerCustomer")
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("CustomerAddresses", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.CustomerPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AutoReorder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DietaryRestrictions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteCategoryIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMenuItemIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("PreferredOrderTime")
                        .HasColumnType("time");

                    b.Property<string>("SpiceLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerPreferences_CustomerId");

                    b.ToTable("CustomerPreferences", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BaseImageUrl");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_MenuItems_CategoryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MenuItems_CreatedAt");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_MenuItems_IsAvailable");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_MenuItems_Name");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_MenuItems_UpdatedAt");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_MenuItems_Category_Name");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("CalculatePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatingUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DecreaseInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IncreaseInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("OrderStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortionCount")
                        .HasColumnType("int");

                    b.Property<int?>("PortionDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("PortionId")
                        .HasColumnType("int");

                    b.Property<string>("PortionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("PriceTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductTimerValueId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(16,3)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Taxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDateTime")
                        .HasDatabaseName("IX_Orders_CreatedDateTime");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("IX_Orders_MenuItemId");

                    b.HasIndex("PortionDetailId")
                        .HasDatabaseName("IX_Orders_PortionDetailId")
                        .HasFilter("[PortionDetailId] IS NOT NULL");

                    b.HasIndex("PortionId")
                        .HasDatabaseName("IX_Orders_PortionId")
                        .HasFilter("[PortionId] IS NOT NULL");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_Orders_TicketId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Component")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Feature")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Page")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacementId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubModule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Create",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8086),
                            Description = "Create users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Create",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Read",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8099),
                            Description = "View users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Read",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Update",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8102),
                            Description = "Update users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Update",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Delete",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8104),
                            Description = "Delete users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Delete",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Activate",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8105),
                            Description = "Activate/deactivate users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.Activate",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 6,
                            Action = "ResetPassword",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8108),
                            Description = "Reset user passwords",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.ResetPassword",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 7,
                            Action = "AssignRoles",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8110),
                            Description = "Assign roles to users",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.AssignRoles",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 8,
                            Action = "ViewAuditLog",
                            Category = "Audit",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8111),
                            Description = "View user audit logs",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Users",
                            Name = "Users.ViewAuditLog",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Create",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8113),
                            Description = "Create roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Create",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Read",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8117),
                            Description = "View roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Read",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 11,
                            Action = "Update",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8119),
                            Description = "Update roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Update",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Delete",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8121),
                            Description = "Delete roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.Delete",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 13,
                            Action = "AssignPermissions",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8122),
                            Description = "Assign permissions to roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.AssignPermissions",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 14,
                            Action = "AssignUsers",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8124),
                            Description = "Assign users to roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Roles",
                            Name = "Roles.AssignUsers",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 15,
                            Action = "Create",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8125),
                            Description = "Create permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Create",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 16,
                            Action = "Read",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8126),
                            Description = "View permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Read",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 17,
                            Action = "Update",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8128),
                            Description = "Update permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Update",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 18,
                            Action = "Delete",
                            Category = "CRUD",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8131),
                            Description = "Delete permissions",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Delete",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 19,
                            Action = "Assign",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8132),
                            Description = "Assign permissions to roles",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "Permissions",
                            Name = "Permissions.Assign",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 20,
                            Action = "Settings",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8133),
                            Description = "Manage system settings",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Settings",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 21,
                            Action = "Backup",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8135),
                            Description = "Create system backups",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Backup",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 22,
                            Action = "Restore",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8136),
                            Description = "Restore system backups",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Restore",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 23,
                            Action = "Logs",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8138),
                            Description = "View system logs",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Logs",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 24,
                            Action = "Monitoring",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8139),
                            Description = "System monitoring access",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Monitoring",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        },
                        new
                        {
                            Id = 25,
                            Action = "Maintenance",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8140),
                            Description = "System maintenance access",
                            IsActive = true,
                            IsDeprecated = false,
                            IsSystemPermission = false,
                            Level = 1,
                            Module = "System",
                            Name = "System.Maintenance",
                            Priority = 0,
                            Scope = "Global",
                            Type = "Functional"
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Portion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxSelection")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("MinSelection")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Portions_CreatedAt");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_Portions_DisplayOrder");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Portions_IsActive");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("IX_Portions_MenuItemId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Portions_UpdatedAt");

                    b.HasIndex("MenuItemId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Portions_MenuItem_Name");

                    b.ToTable("Portions");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.PortionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PortionDetails_CreatedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PortionDetails_Name");

                    b.HasIndex("PortionId")
                        .HasDatabaseName("IX_PortionDetails_PortionId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_PortionDetails_UpdatedAt");

                    b.HasIndex("PortionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_PortionDetails_Portion_Name");

                    b.ToTable("PortionDetails");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentRoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Category = "System",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8283),
                            Description = "Full system access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN",
                            Priority = 1
                        },
                        new
                        {
                            Id = "2",
                            Category = "Admin",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8378),
                            Description = "Administrative access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Priority = 2
                        },
                        new
                        {
                            Id = "3",
                            Category = "Management",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8383),
                            Description = "Management access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            Priority = 3
                        },
                        new
                        {
                            Id = "4",
                            Category = "User",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8387),
                            Description = "Basic user access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER",
                            Priority = 4
                        },
                        new
                        {
                            Id = "5",
                            Category = "Guest",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8390),
                            Description = "Limited guest access",
                            IsActive = true,
                            IsSystemRole = true,
                            Name = "Guest",
                            NormalizedName = "GUEST",
                            Priority = 5
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "1",
                            PermissionId = 1,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5120),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 2,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5126),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 3,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5127),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 4,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5128),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 5,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5129),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 6,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5129),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 7,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5130),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 8,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5131),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 9,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5131),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 10,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5132),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 11,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5132),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 12,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5133),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 13,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5134),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 14,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5134),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 15,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5135),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 16,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5136),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 17,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5137),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 18,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5137),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 19,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5138),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 20,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5140),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 21,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5141),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 22,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5142),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 23,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5143),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 24,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5144),
                            AssignedBy = "System",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 25,
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(5145),
                            AssignedBy = "System",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(1m);

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastOrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastPaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemainingAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(16,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("TaxIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TicketLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TicketStates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(16,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("TransactionDocument_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAddressId")
                        .HasDatabaseName("IX_Tickets_CustomerAddressId")
                        .HasFilter("[CustomerAddressId] IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Tickets_CustomerId")
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Tickets_Date");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Tickets_DepartmentId");

                    b.HasIndex("IsClosed")
                        .HasDatabaseName("IX_Tickets_IsClosed");

                    b.HasIndex("TicketNumber")
                        .HasDatabaseName("IX_Tickets_TicketNumber")
                        .HasFilter("[TicketNumber] IS NOT NULL");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Theme")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81f7395c-3d8f-44cf-9582-e96a1bba0f0a",
                            CreatedAt = new DateTime(2025, 12, 2, 23, 10, 13, 312, DateTimeKind.Utc).AddTicks(8620),
                            Email = "superadmin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            IsActive = true,
                            Language = "en",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@EXAMPLE.COM",
                            NormalizedUserName = "SUPERADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBPLmKungjIisphJlU7bGd7wIDs9VVgJFBMfqKfVjaoOKGDDVGxRxRlPCydv42xQ1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "785d7d57-737e-4ba9-b34b-f713ed123af2",
                            Theme = "light",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@example.com"
                        });
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1",
                            AssignedAt = new DateTime(2025, 12, 2, 23, 10, 13, 382, DateTimeKind.Utc).AddTicks(4977),
                            AssignedBy = "System",
                            IsActive = true,
                            IsPrimary = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Customer", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.CustomerAddress", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Customer", "Customer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.CustomerPreference", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Customer", "Customer")
                        .WithOne("CustomerPreference")
                        .HasForeignKey("DotNet_Starter_Template.Models.Entities.CustomerPreference", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.MenuItem", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Order", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.PortionDetail", "PortionDetail")
                        .WithMany()
                        .HasForeignKey("PortionDetailId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DotNet_Starter_Template.Models.Entities.Portion", "Portion")
                        .WithMany()
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DotNet_Starter_Template.Models.Entities.Ticket", "Ticket")
                        .WithMany("Orders")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Portion");

                    b.Navigation("PortionDetail");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Portion", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.MenuItem", "MenuItem")
                        .WithMany("Portions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.PortionDetail", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Portion", "Portion")
                        .WithMany("PortionDetails")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Ticket", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.CustomerAddress", "CustomerAddress")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DotNet_Starter_Template.Models.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("CustomerAddress");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.UserRole", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DotNet_Starter_Template.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Customer", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("CustomerPreference");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.CustomerAddress", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.MenuItem", b =>
                {
                    b.Navigation("Portions");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Portion", b =>
                {
                    b.Navigation("PortionDetails");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.Ticket", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DotNet_Starter_Template.Models.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
